export const CATEGORY_ICONS = [
  { label: 'Alerts / Notifications', value: 'alert-circle' },
  { label: 'Airfare / Travel', value: 'plane' },
  { label: 'Awards & Bonuses', value: 'award' },
  { label: 'Bank Transfers', value: 'banknote-arrow-up' },
  { label: 'Bills & Utilities', value: 'plug' },
  { label: 'Books & Education', value: 'book-open' },
  { label: 'Bus / Transport', value: 'bus' },
  { label: 'Business / Freelance', value: 'briefcase' },
  { label: 'Calendar', value: 'calendar' },
  { label: 'Charity & Donations', value: 'hand-heart' },
  { label: 'Clock / Time', value: 'clock' },
  { label: 'Clothing & Accessories', value: 'shopping-bag' },
  { label: 'Coffee & Snacks', value: 'coffee' },
  { label: 'Coins / Cash', value: 'coins' },
  { label: 'Credit Card Payments', value: 'credit-card' },
  { label: 'Dining & Restaurants', value: 'utensils' },
  { label: 'Document / File', value: 'file-text' },
  { label: 'Electricity / Gas / Water', value: 'zap' },
  { label: 'Entertainment / Leisure', value: 'music' },
  { label: 'Fitness & Gym', value: 'heart-pulse' },
  { label: 'Food & Groceries', value: 'shopping-cart' },
  { label: 'Fuel / Gasoline', value: 'droplet' },
  { label: 'Gift & Special Occasions', value: 'gift' },
  { label: 'Globe / International', value: 'globe' },
  { label: 'Hair & Beauty', value: 'sparkles' },
  { label: 'Home & Rent', value: 'home' },
  { label: 'Hotel / Accommodation', value: 'building' },
  { label: 'Income / Salary', value: 'wallet' },
  { label: 'Insurance', value: 'shield' },
  { label: 'Investments / Stocks', value: 'trending-up' },
  { label: 'Kids / Children', value: 'baby' },
  { label: 'Loans & Debts', value: 'banknote-x' },
  { label: 'Maps & Travel Fees', value: 'map-pin' },
  { label: 'Miscellaneous / Others', value: 'ellipsis' },
  { label: 'Movies / Cinema', value: 'film' },
  { label: 'Office Supplies', value: 'clipboard' },
  { label: 'Pets & Animals', value: 'paw-print' },
  { label: 'Pharmacy & Medicines', value: 'cross' },
  { label: 'Phone / Internet Bills', value: 'phone' },
  { label: 'Pizza & Fast Food', value: 'pizza' },
  { label: 'Savings / Piggy Bank', value: 'piggy-bank' },
  { label: 'Shopping & Retail', value: 'tag' },
  { label: 'Sports & Outdoor', value: 'activity' },
  { label: 'Taxes / Government Fees', value: 'receipt' },
  { label: 'Tips / Gratuity', value: 'hand-coins' },
  { label: 'Train / Public Transit', value: 'train' },
  { label: 'Transportation', value: 'truck' },
  { label: 'Unlock', value: 'unlock' },
  { label: 'Wallet / Cash', value: 'dollar-sign' },
  { label: 'Euro Currency', value: 'euro' },
  { label: 'Pound Currency', value: 'pound-sterling' },
  { label: 'Circle Dollar', value: 'circle-dollar-sign' },
  { label: 'Charts & Analytics', value: 'chart-bar' },
  { label: 'Pie Chart', value: 'chart-pie' },
  { label: 'Line Chart', value: 'chart-line' },
  { label: 'History / Transactions', value: 'history' },
  { label: 'Lock / Security', value: 'lock' },
  { label: 'Search / Filter', value: 'search' },
  { label: 'Settings / Preferences', value: 'settings' },
  { label: 'Heart / Personal', value: 'heart' },
  { label: 'Star / Favorite', value: 'star' },
]
